### ISSUE TITLE
Endpoints improperly formatted

### ISSUE THREAD

**Issue by Bombware** [Godfather95/chia-rest-api#1]
When following a RESTful pattern API endpoints really shouldn't  have any non text characters. There are exceptions for hyphens, but even then shouldn't. So a url like:
_api/Harvester/get_plots_

should read:
_api/Harvester/GetPlots_

https://specs.openstack.org/openstack/api-wg/guidelines/naming.html#:~:text=REST%20API%20resource%20names&text=Resource%20names%20should%20not%20include,sole%20exception%20is%20the%20hyphen).

**Comment by Godfather95** [comment]
My initial thought was to leave the endpoint names as close to the original RPC Interface, but I think I will change it according to this spec.

**Comment by Bombware** [comment]
That does make sense, but you don't need the end user or consuming application to have any understanding of the data layer. At the service layer you'll want to convert the RPC commands into more application friendly commands. Using the data annotation can illiterate on behaviors as well as overloads.

**Comment by Godfather95** [comment]
Fixed
